name: LaTeX Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download TeX Live installer script
        run: |
          wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz

      - name: Extract the script
        run: |
          tar xvfz install-tl-unx.tar.gz

      - name: Install TeX Live (latest version)
        run: |
          sudo perl ./install-tl-*/install-tl --no-interaction --scheme=null

      - name: Update tlmgr (optional)
        run: |
          sudo /usr/local/texlive/2024/bin/x86_64-linux/tlmgr update --self

      - name: Install additional TeX Live packages (optional)
        run: |
          if [[ -f "docs/latex/latexmkrc" ]]; then
            PACKAGES=$(cat docs/latex/latexmkrc | grep '^\\$usepackage' | sed -E 's/.*qw\((.*)\).*/\1/')
            if [[ ! -z "$PACKAGES" ]]; then
              echo "** Parsed packages from latexmkrc: $PACKAGES"
              sudo /usr/local/texlive/2024/bin/x86_64-linux/tlmgr install $PACKAGES
              echo "** Installed parsed packages from latexmkrc successfully! **"
            else
              echo "** No packages found in latexmkrc. Skipping installation. **"
            fi
          else
            echo "** docs/latex/latexmkrc file not found. Skipping parsing. **"
          fi

      - name: Build LaTeX project
        run: cd docs/latex && make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: latex-build
          path: docs/latex/.build/
